// this file is auto-generated by fetch-profiles.ts
// do not edit manually - changes will be overwritten

import { ProfileData, StrokeDetectionType } from "../common.interfaces";

export const STANDARD_PROFILES: Record<string, ProfileData> = {
    eSPGenericRower: {
        profileId: "dynamic",
        name: "ESP Generic Rower",
        settings: {
            machineSettings: {
                flywheelInertia: 0.1,
                magicConstant: 2.8,
                sprocketRadius: 1.5,
                impulsePerRevolution: 1,
            },
            sensorSignalSettings: {
                rotationDebounceTime: 7,
                rowingStoppedThreshold: 7,
            },
            dragFactorSettings: {
                goodnessOfFitThreshold: 0.97,
                maxDragFactorRecoveryPeriod: 6,
                dragFactorLowerThreshold: 75,
                dragFactorUpperThreshold: 250,
                dragCoefficientsArrayLength: 1,
            },
            strokeDetectionSettings: {
                strokeDetectionType: StrokeDetectionType.Slope,
                impulseDataArrayLength: 3,
                minimumPoweredTorque: 0,
                minimumDragTorque: 0,
                minimumRecoverySlope: 0,
                minimumRecoveryTime: 800,
                minimumDriveTime: 400,
                driveHandleForcesMaxCapacity: 200,
            },
        },
    },
    concept2ModelD: {
        profileId: "genericAir",
        name: "Concept2 Model D",
        settings: {
            machineSettings: {
                flywheelInertia: 0.07848,
                magicConstant: 2.8,
                sprocketRadius: 1.5,
                impulsePerRevolution: 3,
            },
            sensorSignalSettings: {
                rotationDebounceTime: 7,
                rowingStoppedThreshold: 7,
            },
            dragFactorSettings: {
                goodnessOfFitThreshold: 0.97,
                maxDragFactorRecoveryPeriod: 6,
                dragFactorLowerThreshold: 75,
                dragFactorUpperThreshold: 250,
                dragCoefficientsArrayLength: 1,
            },
            strokeDetectionSettings: {
                strokeDetectionType: StrokeDetectionType.Torque,
                impulseDataArrayLength: 6,
                minimumPoweredTorque: 0,
                minimumDragTorque: 0.07,
                minimumRecoverySlope: 0.01,
                minimumRecoveryTime: 800,
                minimumDriveTime: 400,
                driveHandleForcesMaxCapacity: 55,
            },
        },
    },
    kayakFirstOrange: {
        profileId: "kayakFirst",
        name: "KayakFirst Orange",
        settings: {
            machineSettings: {
                flywheelInertia: 0.02527962,
                magicConstant: 2.75,
                sprocketRadius: 2.7,
                impulsePerRevolution: 3,
            },
            sensorSignalSettings: {
                rotationDebounceTime: 7,
                rowingStoppedThreshold: 7,
            },
            dragFactorSettings: {
                goodnessOfFitThreshold: 0.94,
                maxDragFactorRecoveryPeriod: 5,
                dragFactorLowerThreshold: 10,
                dragFactorUpperThreshold: 200,
                dragCoefficientsArrayLength: 1,
            },
            strokeDetectionSettings: {
                strokeDetectionType: StrokeDetectionType.Torque,
                impulseDataArrayLength: 6,
                minimumPoweredTorque: 0,
                minimumDragTorque: 0.09,
                minimumRecoverySlope: 0,
                minimumRecoveryTime: 145,
                minimumDriveTime: 170,
                driveHandleForcesMaxCapacity: 29,
            },
        },
    },
    kayakFirstBlue: {
        profileId: "kayakFirstBlue",
        name: "KayakFirst Blue",
        settings: {
            machineSettings: {
                flywheelInertia: 0.029,
                magicConstant: 2.57,
                sprocketRadius: 2.7,
                impulsePerRevolution: 6,
            },
            sensorSignalSettings: {
                rotationDebounceTime: 5,
                rowingStoppedThreshold: 7,
            },
            dragFactorSettings: {
                goodnessOfFitThreshold: 0.752,
                maxDragFactorRecoveryPeriod: 5,
                dragFactorLowerThreshold: 10,
                dragFactorUpperThreshold: 200,
                dragCoefficientsArrayLength: 4,
            },
            strokeDetectionSettings: {
                strokeDetectionType: StrokeDetectionType.Torque,
                impulseDataArrayLength: 10,
                minimumPoweredTorque: 0,
                minimumDragTorque: 0.18,
                minimumRecoverySlope: 0,
                minimumRecoveryTime: 145,
                minimumDriveTime: 170,
                driveHandleForcesMaxCapacity: 56,
            },
        },
    },
    kettler07982500: {
        profileId: "kettlerStroker",
        name: "Kettler 07982-500",
        settings: {
            machineSettings: {
                flywheelInertia: 0.0293,
                magicConstant: 2.8,
                sprocketRadius: 1.6875,
                impulsePerRevolution: 4,
            },
            sensorSignalSettings: {
                rotationDebounceTime: 8,
                rowingStoppedThreshold: 7,
            },
            dragFactorSettings: {
                goodnessOfFitThreshold: 0.8,
                maxDragFactorRecoveryPeriod: 6,
                dragFactorLowerThreshold: 75,
                dragFactorUpperThreshold: 2,
                dragCoefficientsArrayLength: 10,
            },
            strokeDetectionSettings: {
                strokeDetectionType: StrokeDetectionType.Torque,
                impulseDataArrayLength: 6,
                minimumPoweredTorque: 0,
                minimumDragTorque: 0.4,
                minimumRecoverySlope: 0,
                minimumRecoveryTime: 800,
                minimumDriveTime: 400,
                driveHandleForcesMaxCapacity: 68,
            },
        },
    },
    "oldDanube2025/6M": {
        profileId: "oldDanube",
        name: "OldDanube 2025/6M",
        settings: {
            machineSettings: {
                flywheelInertia: 0.0899,
                magicConstant: 2.57,
                sprocketRadius: 3.2,
                impulsePerRevolution: 6,
            },
            sensorSignalSettings: {
                rotationDebounceTime: 4,
                rowingStoppedThreshold: 10,
            },
            dragFactorSettings: {
                goodnessOfFitThreshold: 0.67,
                maxDragFactorRecoveryPeriod: 4,
                dragFactorLowerThreshold: 10,
                dragFactorUpperThreshold: 200,
                dragCoefficientsArrayLength: 5,
            },
            strokeDetectionSettings: {
                strokeDetectionType: StrokeDetectionType.Torque,
                impulseDataArrayLength: 9,
                minimumPoweredTorque: 0,
                minimumDragTorque: 0.08,
                minimumRecoverySlope: 0,
                minimumRecoveryTime: 145,
                minimumDriveTime: 160,
                driveHandleForcesMaxCapacity: 59,
            },
        },
    },
};

export const CUSTOM_PROFILE_KEY = "custom";
